version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:80"  # Map container's port 80 to host's 5173
    networks:
      - blog
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "4001:4001"
    networks:
      - blog
  
networks:
  blog:
    driver: bridge
