FROM node:20 AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

# RUN npm install
COPY . .

#Stage 2

FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app .

EXPOSE 4001

CMD ["npm", "start"]