FROM node:20 AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --only=production

# RUN npm install
COPY . .

FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app ./

EXPOSE 4001

CMD ["npm", "start"]