kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend-deployment
  namespace: blog-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: blogapp-backend
        image: wiings09/backend-blogapp
        ports:
        - containerPort: 4001
        env:
          - name: PORT
            value: "4001"
          - name: MONGO_URI
            value: "mongodb://mongo:27017/blog-db"
          - name: CLOUD_NAME
            value: "ddtpareis"
          - name: CLOUD_API_KEY
            value: "your-key"
          - name: CLOUD_SECRET_KEY
            value: "your-secret-key"
          - name: JWT_SECRET_KEY
            value: "your-secret-key"
          - name: FRONTEND_URL
            value: "http://65.2.31.80:5173"
          - name: NODE_ENV
            value: production
