kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend-deployment
  namespace: blog-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: blogapp-backend
        image: wiings09/blogapp-backend
        ports:
        - containerPort: 4001
        env:
          - name: PORT
            value: "4001"
          - name: MONGO_URI
            value: "mongodb://mongo:27017/blog-db"
          - name: CLOUD_NAME
            value: "ddtpareis"
          - name: CLOUD_API_KEY
            value: "911794411167976"
          - name: CLOUD_SECRET_KEY
            value: "6iITPdBeV8q_CfUvhEDLIH_JQgE"
          - name: JWT_SECRET_KEY
            value: "9cAtQQD6Nv7fngeF49L+cncU7DfR23V6y/rhoX6aL9k="
          - name: FRONTEND_URL
            value: "http://frontend:5173"
          - name: NODE_ENV
            value: production
