name: CI/CD Pipeline for BlogApp

on:
  push:
    branches:
      - k8s-prod

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build frontend image
        run: docker build -t wiings09/frontend-blogapp ./frontend

      - name: Build backend image
        run: docker build -t wiings09/backend-blogapp ./backend

  push:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push frontend image
        run: docker push wiings09/frontend-blogapp

      - name: Push backend image
        run: docker push wiings09/backend-blogapp

  deploy:
    needs: push
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create namespace if not exists
        run: |
          kubectl get ns blog-app || kubectl create ns blog-app

      - name: Deploy all Kubernetes manifests
        run: |
          kubectl apply -f k8s/ -n blog-app
